name: Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      # ---- IMPORTANT: do NOT use ./gradlew here ----
      - name: Download Gradle (no wrapper)
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: "8.7"

      - name: Build Debug APK (no wrapper)
        run: |
          gradle --version
          gradle assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
