name: Automatic Dependency Submission

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Disabled on purpose (wrapper missing)."
